name: Jekyll site CI

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Checkout PHR repo
      uses: actions/checkout@v2
      with:
        repository: JYVSECTEC/phr-model
        path: phr-model

    - name: Checkout PHR-model-links repo
      uses: actions/checkout@v2
      with:
        repository: JYVSECTEC/phr-model-links
        path: phr-model-links
          
    - name: Copy and prepare the sites
      working-directory: build/
      run: |
        wget https://raw.githubusercontent.com/mitre/cti/master/enterprise-attack/enterprise-attack.json -qO enterprise-attack.json
        python3 phr_to_json.py ../phr-model/ \
            --fill-html-template \
            --html-template-file vue_template.html \
            --resolve-mitre-attack-names \
            --output phr.html
        python3 link_to_json.py phr.html \
            -s ../phr-model-links \
            -m https://raw.githubusercontent.com/JYVSECTEC/PHR-model-links/main \
            -l
        cp ../phr-model/README.md index.md
        
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v $(pwd)/build:/srv/jekyll \
        -v $(pwd)/docs:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && JEKYLL_ENV=production jekyll build --future"

    - name: Push the changes
      run: |
        git config user.name "workflow.bot"
        git config user.email "workflow.bot"
        git add docs/*
        git commit -m "Publish the site"
        git push
